window.esdocSearchIndex = [
  [
    "chatwork-utils/src/basechatwork.js~basechatwork",
    "class/src/baseChatwork.js~baseChatwork.html",
    "<span>baseChatwork</span> <span class=\"search-result-import-path\">chatwork-utils/src/baseChatwork.js</span>",
    "class"
  ],
  [
    "chatwork-utils/src/chatwork.js~chatwork",
    "class/src/chatwork.js~chatwork.html",
    "<span>chatwork</span> <span class=\"search-result-import-path\">chatwork-utils/src/chatwork.js</span>",
    "class"
  ],
  [
    "chatwork-utils/src/chatworkro.js~chatworkro",
    "class/src/chatworkRo.js~chatworkRo.html",
    "<span>chatworkRo</span> <span class=\"search-result-import-path\">chatwork-utils/src/chatworkRo.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/basechatwork.js",
    "file/src/baseChatwork.js.html",
    "src/baseChatwork.js",
    "file"
  ],
  [
    "src/basechatwork.js~axios.requestconfig",
    "https://github.com/mzabriskie/axios#request-config",
    "src/baseChatwork.js~axios.requestConfig",
    "external"
  ],
  [
    "src/basechatwork.js~basechatwork#constructor",
    "class/src/baseChatwork.js~baseChatwork.html#instance-constructor-constructor",
    "src/baseChatwork.js~baseChatwork#constructor",
    "method"
  ],
  [
    "src/basechatwork.js~basechatwork#instance",
    "class/src/baseChatwork.js~baseChatwork.html#instance-member-instance",
    "src/baseChatwork.js~baseChatwork#instance",
    "member"
  ],
  [
    "src/chatwork.js",
    "file/src/chatwork.js.html",
    "src/chatwork.js",
    "file"
  ],
  [
    "src/chatwork.js~chatwork#approveincomingrequest",
    "class/src/chatwork.js~chatwork.html#instance-method-approveIncomingRequest",
    "src/chatwork.js~chatwork#approveIncomingRequest",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#createchatroom",
    "class/src/chatwork.js~chatwork.html#instance-method-createChatroom",
    "src/chatwork.js~chatwork#createChatroom",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#createmessagechatroom",
    "class/src/chatwork.js~chatwork.html#instance-method-createMessageChatroom",
    "src/chatwork.js~chatwork#createMessageChatroom",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#createtaskchatroom",
    "class/src/chatwork.js~chatwork.html#instance-method-createTaskChatroom",
    "src/chatwork.js~chatwork#createTaskChatroom",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#deletechatroom",
    "class/src/chatwork.js~chatwork.html#instance-method-deleteChatroom",
    "src/chatwork.js~chatwork#deleteChatroom",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#leavechatroom",
    "class/src/chatwork.js~chatwork.html#instance-method-leaveChatroom",
    "src/chatwork.js~chatwork#leaveChatroom",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#modifychatroommembers",
    "class/src/chatwork.js~chatwork.html#instance-method-modifyChatroomMembers",
    "src/chatwork.js~chatwork#modifyChatroomMembers",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#rejectincomingrequest",
    "class/src/chatwork.js~chatwork.html#instance-method-rejectIncomingRequest",
    "src/chatwork.js~chatwork#rejectIncomingRequest",
    "method"
  ],
  [
    "src/chatwork.js~chatwork#updatechatroom",
    "class/src/chatwork.js~chatwork.html#instance-method-updateChatroom",
    "src/chatwork.js~chatwork#updateChatroom",
    "method"
  ],
  [
    "src/chatworkro.js",
    "file/src/chatworkRo.js.html",
    "src/chatworkRo.js",
    "file"
  ],
  [
    "src/chatworkro.js~chatworkro#getfileinfo",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-getFileInfo",
    "src/chatworkRo.js~chatworkRo#getFileInfo",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#getmessageinfo",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-getMessageInfo",
    "src/chatworkRo.js~chatworkRo#getMessageInfo",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#getmystatus",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-getMyStatus",
    "src/chatworkRo.js~chatworkRo#getMyStatus",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#getroominfo",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-getRoomInfo",
    "src/chatworkRo.js~chatworkRo#getRoomInfo",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#gettaskinfo",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-getTaskInfo",
    "src/chatworkRo.js~chatworkRo#getTaskInfo",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listincomingrequests",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listIncomingRequests",
    "src/chatworkRo.js~chatworkRo#listIncomingRequests",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listmycontacts",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listMyContacts",
    "src/chatworkRo.js~chatworkRo#listMyContacts",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listmymessages",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listMyMessages",
    "src/chatworkRo.js~chatworkRo#listMyMessages",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listmytasks",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listMyTasks",
    "src/chatworkRo.js~chatworkRo#listMyTasks",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listroomfiles",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listRoomFiles",
    "src/chatworkRo.js~chatworkRo#listRoomFiles",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listroommembers",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listRoomMembers",
    "src/chatworkRo.js~chatworkRo#listRoomMembers",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listroommessages",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listRoomMessages",
    "src/chatworkRo.js~chatworkRo#listRoomMessages",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#listroomtasks",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-listRoomTasks",
    "src/chatworkRo.js~chatworkRo#listRoomTasks",
    "method"
  ],
  [
    "src/chatworkro.js~chatworkro#me",
    "class/src/chatworkRo.js~chatworkRo.html#instance-method-me",
    "src/chatworkRo.js~chatworkRo#me",
    "method"
  ]
]